#!/usr/bin/env python

def main():
    # import rospy packages
    import rospy
    import auv_main.msg as messages
    import auv_main.srv as services
    from std_msgs.msg import String
    from geometry_msgs.msg import Vector3Stamped

    # import main_module packages
    # core
    from main_module.gyro.ros_middleman import Middleman as Gyro
    from main_module.odometer.ros_middleman import Middleman as Odometer
    from main_module.propulsion.ros_middleman import Middleman as Propulsion
    # planning
    from main_module.planning.s2018 import coach
    # subsystems
    from main_module.subsystems.ros_middlemen import Vision

    # initialize main_module classes
    gyro = Gyro()
    odometer = Odometer()
    propulsion = Propulsion(gyro)
    vision = Vision()

    # configure main_module classes using config.json
    import rospkg
    path = rospkg.RosPack().get_path('auv_main')
    import json
    conf = open(path + '/nodes/config.json').read()
    conf = json.loads(conf)
    gyro.configure_message_outlets(conf['gyro']['x'], conf['gyro']['y'], conf['gyro']['z'])
    odometer.configure_message_outlets(conf['odometer']['x'], conf['odometer']['y'], conf['odometer']['z'])
    Propulsion.configure_class_params(conf['translationalPID'], conf['rotationalPID'], conf['maxYawErrorWhileMoving'])

    # select a strategy
    strategy = coach.list_of_strategies()[2]
    strategy = coach.initialize(strategy, gyro, odometer)

    rospy.init_node('main_module', anonymous = False)
    rospy.Subscriber('ngimu/euler', Vector3Stamped, gyro.callback)
    rospy.Subscriber('imu_kalman/xyz', Vector3Stamped, odometer.callback)
    rospy.Subscriber("cv_inference/cv_detection", String, vision.callback)# TODO is this correct node name

    rospy.wait_for_service('motion_controller/InitMotors')
    rospy.wait_for_service('motion_controller/SetEnabled')
    rospy.wait_for_service('motion_controller/Zero')
    rospy.wait_for_service('motion_controller/SetForwardsPower')
    rospy.wait_for_service('motion_controller/SetYawAngle')
    rospy.wait_for_service('motion_controller/SetDepth')
    rospy.wait_for_service('motion_controller/SetRollPitchAngles')

    # TODO could we use the flag persistent=true in all of these calls
    # if so, make sure to call close() later on
    ros_init_motors = rospy.ServiceProxy('motion_controller/InitMotors', services.InitMotors)
    ros_set_enabled = rospy.ServiceProxy('motion_controller/SetEnabled', services.SetEnabled)
    ros_zero = rospy.ServiceProxy('motion_controller/Zero', services.Zero)
    ros_set_forwards_power = rospy.ServiceProxy('motion_controller/SetForwardsPower', services.SetForwardsPower)
    ros_set_yaw_angle = rospy.ServiceProxy('motion_controller/SetYawAngle', services.SetYawAngle)
    ros_set_depth = rospy.ServiceProxy('motion_controller/SetDepth', services.SetDepth)
    ros_set_roll_pitch_angles = rospy.ServiceProxy('motion_controller/SetRollPitchAngles', services.SetRollPitchAngles)

    ros_init_motors()
    ros_set_enabled(True)
    ros_zero()

    rate = rospy.Rate(10)# Hz
    while not rospy.is_shutdown():
        strategy.run(propulsion, [vision])#[])

        message = propulsion.bundle_for_ros(messages.desired_motion())
        rospy.loginfo(message)

        ros_set_forwards_power(100*message.desired_percent_speed)
        ros_set_yaw_angle(message.desired_degrees_yaw)
        ros_set_depth(odometer.z + message.desired_delta_depth_meters)

        rate.sleep()

    # ros_init_motors.close()
    # ros_set_enabled.close()
    # ros_zero.close()
    # ros_set_forwards_power.close()
    # ros_set_yaw_angle.close()
    # ros_set_depth.close()
    # ros_set_roll_pitch_angles.close()


if __name__ == '__main__':
    main()
